### ISSUE TITLE
Error al consultar todos los Genes de getAllGenes() Bug Report 🐞

### ISSUE THREAD

**Issue by Galarcon128** [regulondbunam/GraphQL-api#26]
# Error al consultar todos los Genes de getAllGenes()
## Describe the bug

devuelve error hacer una consulta en el datamart getAllGenes al pedir todos los genes o la ultima pagina

## To reproduce the bug

Error al realizar una consulta con el siguiente query:

````gql
{
  getAllGenes(limit: 10, page: 470) {
    data {
      id
      gene {
        name
        synonyms
        note
      }
      products {
        name
        id
      }
    }
    pagination {
      limit
      currentPage
      firstPage
      lastPage
      totalResults
      hasNextPage
    }
  }
}

````

## Expected behavior

Se espera que se devuelva una lista de genes pero devuelve el siguiente error

```` js
"errors": [
    {
      "message": "Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.",
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "openTools",
        "query": "{getAllGenes(limit:10 page:400){data{id gene{name synonyms note}products{name id}}pagination{limit currentPage firstPage lastPage totalResults hasNextPage}}}",
        "variables": {},
        "exception": {
          "stacktrace": [
            "GraphQLError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.",
            "    at downstreamServiceError (/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:267:12)",
            "    at /app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:57",
            "    at Array.map (<anonymous>)",
            "    at sendOperation (/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:44)",
            "    at processTicksAndRejections (node:internal/process/task_queues:94:5)",
            "    at async executeFetch (/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:111:41)",
            "    at async executeNode (/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:82:17)",
            "    at async Object.executeQueryPlan (/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:22:27)",
            "    at async Object.ApolloGateway.executor (/app/node_modules/@apollo/gateway/dist/index.js:109:30)"
          ]
        }
      }
    }
  ]
````

#### Web Services to solve bug

- getAllGenes
  - 

---

###### Additional context

Consulta realizada en el playground en la version 0.5.1

**Comment by andresloal** [comment]
Se revisará a la brevedad posible, gracias por reportarlo! 👍🏼 😄

**Comment by andresloal** [comment]
Tras revisar los posibles factores que llevan a este error se determinó que se debe a la ausencia de los indexes en los datamarts. Cuando un datamart no tiene definido un index con el nombre provoca este tipo de errores al querer realizar el ordenamiento por orden alfabético al intentar resolver la consulta. Se tendrá especial cuidado cuando se generen los dump de los datamarts verificando que se encuentren los indexes en cada uno de ellos. 

Saludos :)
